### ISSUE TITLE
Simulation get slower using actual population from the polygon blocks

### ISSUE THREAD

**Issue by gamalielpalomo** [CityScienceLab-GDL/cityscope-ccu#1]
If we use the actual number of people living in the polygon, the simulation gets slower.

**Comment by agrignard** [comment]
Isn't it simply because there is more people? More agent means more computation so a slower simulation

**Comment by gamalielpalomo** [comment]
Yes, that is the reason. In this case study we use the current population from the polygon in order to compute the indicators. In other tables, do you use the whole population or just a sample?

**Comment by agrignard** [comment]
Is this issue resolved? if not can you provide more context?

**Comment by gamalielpalomo** [comment]
previously we needed to run many "people" agents since these were the ones that calculated the mobility accessibility indicator, however that made the simulation slow. It was decided to calculate the indicator based on space (not on people), which makes it possible to reduce the number of "people" agents.

**Comment by agrignard** [comment]
ok great so let's close this issue too?
