### ISSUE TITLE
SHP validation model

### ISSUE THREAD

**Issue by gamalielpalomo** [CityScienceLab-GDL/cityscope-ccu#11]
@LAAP  and @agrignard: We had a meeting today and talked about how to validate that roads and block shapes files are correct (i.e. check that they does not have open lines, etc.).

**Comment by LAAP** [comment]
Hi @agrignard , do you remember the Methodology that we used for finding out if the road network vectors and polygons where "closed" at the Cooper Hewitt table? I think it was a python file + a GAMA model. Can you help us tow see if we can use it in Guadalajara?

**Comment by agrignard** [comment]
Yep, @gamalielpalomo  you can have a look at this model in the library ```Clean Line Network.gaml```

**Comment by LAAP** [comment]
Thanks @agrignard !!!

**Comment by agrignard** [comment]
@gamalielpalomo did you manage to clean your network? If yes we can close this issue

**Comment by gamalielpalomo** [comment]
I have solved this problem by now building the roads network using `as_intersection_graph` which works even when the shp lines are not all "closed".

**Comment by agrignard** [comment]
Ok so we can close we can close this issue
