### ISSUE TITLE
Indicator: Diversity

### ISSUE THREAD

**Issue by gamalielpalomo** [CityScienceLab-GDL/cityscope-ccu#4]
Indicators related to diversity
- [x] Hab/Emp ratio
- [x] Night activities
- [x] Daytime activities
- [x] Third activities
- [x] Knowledge activities

These indicators will be calculated using Shannon index

**Comment by LAAP** [comment]
I agree, Please, let me know what if the issue if any, or how can I help.

I am following the development of the indicators at:
https://docs.google.com/spreadsheets/d/1jKwGme6Be_x_L1tqHRgWMWzzBPTaU0lI/edit#gid=1112802940

**Comment by gamalielpalomo** [comment]
All these indicators have been incorporated into the latest version, I will close it.
