### ISSUE TITLE
Indicator: Mobility

### ISSUE THREAD

**Issue by gamalielpalomo** [CityScienceLab-GDL/cityscope-ccu#6]
- [x] public transport coverage
- [x] Km of roads per number of inhabitants
- [x] km of roads per km2
- [x] % percentage of blocks with sidewalk

**Comment by LAAP** [comment]
I agree, Please, let me know what if the issue if any, or how can I help.

I am following the development of the indicators at:
https://docs.google.com/spreadsheets/d/1jKwGme6Be_x_L1tqHRgWMWzzBPTaU0lI/edit#gid=1112802940

**Comment by gamalielpalomo** [comment]
All these indicators have been solved in the last version. I will close it.
